# Generated by Django 5.2.2 on 2025-06-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicalCaseTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("doctor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FlashCardTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalCaseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tableofcontents", models.CharField(max_length=200)),
                ("gatherquipments", models.CharField(max_length=200)),
                ("introduction", models.TextField()),
                ("generalinspections", models.TextField()),
                ("clearinspection", models.TextField()),
                ("palpation", models.TextField()),
                ("finalexamination", models.TextField()),
                ("references", models.TextField()),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="notes2.clinicalcasetopic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlashCardContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                (
                    "flashcard",
                    models.ImageField(blank=True, null=True, upload_to="flashcard/"),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="notes2.flashcardtopic",
                    ),
                ),
            ],
        ),
    ]
