# Generated by Django 5.2.2 on 2025-06-11 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MCQContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PREMIUM", "Premium")],
                        max_length=10,
                    ),
                ),
                (
                    "mcqcontentpic",
                    models.ImageField(
                        blank=True, null=True, upload_to="mcqcontentpic/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MCQTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("doctor", models.CharField(max_length=100)),
                ("video_count", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MCQQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(max_length=200)),
                ("option_4", models.CharField(max_length=200)),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Option 1"),
                            (2, "Option 2"),
                            (3, "Option 3"),
                            (4, "Option 4"),
                        ]
                    ),
                ),
                (
                    "mcq_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="notes.mcqcontent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mcqcontent",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mcqs",
                to="notes.mcqtopic",
            ),
        ),
        migrations.CreateModel(
            name="VideoContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("sub", models.CharField(max_length=100)),
                ("timer", models.PositiveIntegerField(help_text="Duration in seconds")),
                (
                    "status",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PREMIUM", "Premium")],
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField()),
                (
                    "videocontentpic",
                    models.ImageField(
                        blank=True, null=True, upload_to="videocontentpic/"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="notes.videotopic",
                    ),
                ),
            ],
        ),
    ]
