# Generated by Django 5.2.2 on 2025-06-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videotopic",
            name="doctor",
            field=models.CharField(default="Dr.Ranchodas", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videotopic",
            name="video_count",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
