# Generated by Django 5.2.2 on 2025-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_videotopic_doctor_videotopic_video_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videotopic",
            name="video_count",
            field=models.CharField(max_length=100),
        ),
    ]
