# Generated by Django 5.2.2 on 2025-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_videotopic_video_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocontent",
            name="videocontentpic",
            field=models.ImageField(
                blank=True, null=True, upload_to="videocontentpic/"
            ),
        ),
    ]
