# Generated by Django 5.2.2 on 2025-06-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_batch_bookmark_comment_country_like_mcqday_mcqoption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
    ]
